#!/bin/bash
## gbr script mocking gbr install in container
# It only works with:
# gbr pool ls -d
# gbr file ls -i D5B58980A3E311EBBA0AB026285E5610
# gbr file ls -i D5B58980A3E311EBBA0AB026285E5610 -d
## WARNING!!!!
## These are hard coded, incredibly brittle & site2ally inflexible

# Consts
DATASETID=41545AB0788A11ECBD0700155D014E0D
FILEID=D5B58980A3E311EBBA0AB026285E5610
BAD_FILEID=3D3D0900791F11ECB6BD00155D014E0D
FILEID_IN_WRONG_DS=3E4FF671B44E11ED86FF00155D015E0D
FILENAME=05043fe1-00000006-2f8630d0-608630d0-67d25000-ab66ac56
NOTAFILEID=not_a_file_id

# Vars
NUMARGS="$#"
CMD="$1"
ID="$4"


# Outputs

read -r -d '' POOL << 'EOF'
====== + Pools  in datalake 'nmr' ======

- pool01 ( disk pool, primary )
 == General ==
   - description:
   - creation date:             Tue Jan 18 23:12:53 EST 2022
   - primary:                   true
   - ID:                        41545AB0788A11ECBD0700155D014E0D
   - parent datalake:           nmr (ID: 0E544860788911ECBD0700155D014E0D)
EOF

read -r -d '' FILE_DETAIL << 'EOF'
1 - FILENAME (file id: FILEID)
    version:            0
    type:               file
    parent folder id:   3E4FF671B44E11ED86FF00155D014E0D
    parent folder name: 6132
    parent id:          41545AB0788A11ECBD0700155D014E0D
    original file name: null
    file URI:           null
    fan URI:            ftp://user@192.168.101.210:2121/download/2023_02/1eeb7769-fdb1-4313-8d76-ec719ad7a44c/mnt/nas01/FILENAME
    pool id:            41545AB0788A11ECBD0700155D014E0D
    legal hold:         Enabled=false OwnerID=null MatterID=null Start=Sat Jan 01 05:00:00 EST 1 Release=Sat Jan 01 05:00:00 EST 1
    policies:
      RetentionDisposition(null, enabled='true')(start='Mon Feb 27 19:08:25 EST 2023', end='Sat Jan 27 19:08:25 EST 2029', neverDispose='true')
    file hash:
EOF

read -r -d '' FILE_IN_WRONG_DS << 'EOF'
1 - 05043fe1-00000006-2f8630d0-608630d0-67d25000-ab66ac56 (file id: 3E4FF671B44E11ED86FF00155D015E0D)
    version:            0
    type:               file
    parent folder id:   3E4FF671B44E11ED86FF00155D015E0D
    parent folder name: 6132
    parent id:          396862B0791111ECA62400155D014E11
    original file name: null
    file URI:           null
    fan URI:            ftp://user@192.168.101.210:2121/download/2023_02/1eeb7769-fdb1-4313-8d76-ec719ad7a44c/mnt/nas01/05043fe1-00000006-2f8630d0-608630d0-67d25000-ab66ac56
    pool id:            41545AB0788A11ECBD0700155D014E0D
    legal hold:         Enabled=false OwnerID=null MatterID=null Start=Sat Jan 01 05:00:00 EST 1 Release=Sat Jan 01 05:00:00 EST 1
    policies:
      RetentionDisposition(null, enabled='true')(start='Mon Feb 27 19:08:25 EST 2023', end='Sat Jan 27 19:08:25 EST 2029', neverDispose='true')
    file hash:
EOF

read -r -d '' FILE << 'EOF'
1 - FILENAME (file id: FILEID)
EOF

read -r -d '' FILE_ERR << 'EOF'
java.lang.NumberFormatException: For input string: "no"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at ttl.nds.java.common.StringUtils.fromHexString(StringUtils.java:139)
        at TTL.Nds.Mb.Objects.Common.Nuid.Nuid.<init>(Nuid.java:35)
        at com.trm.gb.restapi.client.commands.file.FileListCommand.call(FileListCommand.java:84)
        at com.trm.gb.restapi.client.commands.file.FileListCommand.call(FileListCommand.java:36)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at com.trm.gb.restapi.client.commands.GbrcCommand.main(GbrcCommand.java:71)
EOF

function get_pool {
    echo "$POOL"
}

function get_file {
    local ID="$1"
    if [[ "$ID" == "$FILEID" ]]
    then
        echo "$FILE" | sed "s/FILEID/"$ID"/g" | sed "s/FILENAME/"$FILENAME"/g"
    else 
        # Hack to handle testing for both local devcontainer & build container
        if [ -f "/workspaces/process_async_ds/gbr.list" ]
        then 
            LINE=$(cat /workspaces/process_async_ds/gbr.list | grep $ID)
        elif [ -f "/usr/src/app/gbr.list" ]
        then
            LINE=$(cat /usr/src/app/gbr.list | grep $ID)
        fi
        FN=$(echo $LINE | cut -d',' -f2)
        echo "$FILE" | sed "s/FILEID/"$ID"/g" | sed "s/FILENAME/"$FN"/g"
    fi
}



function get_file_detail {
    local ID="$1"
    echo "$FILE_DETAIL" | sed "s/FILEID/"$ID"/g"
}

function get_file_in_wrong_ds {
    echo "$FILE_IN_WRONG_DS"
}

function get_bad_file_id {
    exit
}


function get_file_err {
    >&2 echo "$FILE_ERR" 
}

#sleep 2
if [ "$CMD" = "pool" ] 
then
    get_pool
elif [ "$CMD" = "file" ]
then 
    if [ "$ID" = "$BAD_FILEID" ]
    then
        get_bad_file_id
    elif [ "$ID" = "$FILEID_IN_WRONG_DS" ]
    then
        get_file_in_wrong_ds
    elif [ "$ID" = "$NOTAFILEID" ]
    then
        get_file_err
    elif [ "$NUMARGS" = "4" ] 
    then
        get_file $ID
    elif [ "$NUMARGS" = "5" ]
    then
        get_file_detail $ID
    fi

fi
